accounts/urls.py

from django.urls import re_path as url
from . import views
# from django.contrib.auth.views import login , logout
# from django.contrib.auth.views import LoginView ,LoginView
from django.contrib.auth import views as auth_views
# from django.contrib.auth.views import login , logout
app_name = 'accounts'
urlpatterns = [
    
    url(r'^$', views.home , name='home'),
    # url(r'^login/$', login,{'template_name': 'login.html'}, name = 'login'),
    url('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.register , name='register'),
    url(r'^(?P<slug>[-\w]+)/$', views.profile  , name='profile'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit_profile  , name='edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$', views.change_password  , name='change_password'),
]


notes/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes_App.urls' ,namespace= 'notes')),
    path('', include('home.urls' ,namespace= 'home')),
    path('accounts/', include('accounts.urls' ,namespace= 'accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import  slugify
from django.db.models.signals import  post_save
# Create your models here.
class Profile(models.Model):
    user      = models.OneToOneField(User,on_delete=models.CASCADE)
    slug      = models.SlugField(null=True, blank= True)
    headline = models.CharField(blank=True,max_length=100)
    bio       = models.TextField(blank= True)
    userphoto = models.ImageField(upload_to='profile-img',default='')
    join_date = models.DateTimeField(blank=True , default=datetime.datetime.now)
    
    def save(self, *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.user)
        super(Profile, self).save(*args, **kwargs)
        
    def __str__(self):
        return '%s' %(self.user)    
    
    
### signal 
def createprofile(sender , **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user= kwargs['instance'])

post_save.connect(createprofile, sender=User)        


accounts/forms.py

from django import forms
from . import models
from django.contrib.auth.models import  User


class UserForm(forms.ModelForm):
    class  Meta:
        model  = User
        fields = [
            'username' , 'first_name', 'last_name', 'email'
        ]



class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = [
            'headline','bio','userphoto'
        ]

notes_App/forms.py
from django import forms
from .models import Note , Comment
from django.contrib import admin
from ckeditor.widgets import CKEditorWidget

class AddNote(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget() )
    class Meta:
        model = Note
        fields = ['title', 'content', 'tags','img','active']


class AddComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

accounts/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth.forms import UserCreationForm , PasswordChangeForm
from django.contrib.auth import authenticate , login
from .models import Profile
from django.shortcuts import get_object_or_404
from .forms import UserForm , ProfileForm
from django.contrib.auth.models import User
from django.contrib import messages
from notes_App.models import Note
# Create your views here.
def home(request):
    pass



def register(request):
    if request.method == "POST":
        
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username =form.cleaned_data.get('username') 
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password= password)
            login(request, user)
            messages.info(request, 'register created successfully')
            return redirect('/notes')   
    else:
        form = UserCreationForm
    if request.user.is_authenticated:
        user = request.user
        profile = get_object_or_404(Profile , user=user)
        context = {
            'form': form,
            'profile':profile,
        }
    else:
        context = {
            'form': form,
        }
    return render(request,'signup.html', context)
    

def profile(request, slug):
        
        
        profile = get_object_or_404(Profile, slug=slug)
        context = {
            'profile': profile
        }
        
        return render(request,'profile.html',context)
    
def edit_profile(request,slug):
    profile = get_object_or_404(Profile, slug=slug)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST,request.FILES,instance=profile) 
        if user_form.is_valid() and profile_form.is_valid() :
            user_form.save()
            profile_form.save()
            messages.info(request, 'Profile Updated successfully')
            # new_profile.user = request.user
            # new_profile.save()
            return redirect('/')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)  
        
        context = {
            'user_form':user_form,
            'profile_form':profile_form,
            'profile': profile,
            
        }  
        
        return render(request,'edit_profile.html',context)
    
    
def change_password(request,slug):
    profile = get_object_or_404(Profile, slug=slug)
    if request.method == 'POST':
        form =  PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            
            form.save()
            messages.info(request, 'Password Updated successfully')
            return redirect('/')
    else:
        form =  PasswordChangeForm(user=request.user)
    
    context = {
        'form': form,
        'profile':profile,
    }
    return render(request,'change_password.html',context)

accounts/templates/change_password.html

{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
    <div class="section-headline text-center" style="padding-top: 100px;">
        <h2>Change Password </h2>                 
    </div>
<form method="post" >
    <a style="background-color:#222;color:#fff;font-size:16px;padding:10px;border-radius:6px" href="{% url 'accounts:profile' profile.slug %} "> Back</a> 
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" style="margin:50px 0 ;">
        Change Password
    </button>
    
    {% endbuttons %}
</form>

{% endblock body %}

accounts/templates/edit_profile.html


{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
<div class="section-headline text-center" style="padding-top: 100px;">
    <h2>Edit your profile </h2>                 
</div>

<form method="post" enctype="multipart/form-data">
    <a style="background-color:#222;color:#fff;font-size:16px;padding:10px;border-radius:6px" href="{% url 'accounts:profile' profile.slug %} "> Back</a>
    {% csrf_token %}
    {% bootstrap_form user_form %}
    
    {% bootstrap_form profile_form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" style="margin:50px 0 ;">
        Save Changes
    </button>
    
    {% endbuttons %}
</form>
{% endblock body %}


accounts/templates/login.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
<div class="section-headline text-center" style="padding-top: 100px;">
    <h2>Login Form </h2>                 
</div>
    <div id="login">
        <h3 class="text-center text-white pt-5">Login form</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        
                        <form id="login-form" class="form" action="" method="post">
                            {% csrf_token %}
                            <h3 class="text-center text-info">Login</h3>
                            {% bootstrap_form form %}
                            <div class="form-group">
                                {% comment %} <label for="remember-me" class="text-info"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br> {% endcomment %}
                                {% buttons %}
                                <button type="submit" class="btn btn-primary " style="margin:50px 0 ;">
                                    Login
                                </button>
                                
                                {% endbuttons %}
                                {% comment %} <input type="submit" name="submit" class="btn btn-info btn-md" value="Login"> {% endcomment %}
                            </div>
                            <div id="register-link" class="text-right">
                                <a href="{% url 'accounts:register' %}" class="text-info">Register here</a>
                                <br>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

accounts/templates/profile.html

{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
    <div class="section-headline text-center" style="padding-top: 100px;">
        <h2>profile Details </h2>                 
    </div>




        <div class="container prof_con" >
            <div class="row profile prof_con">
                <div class="col-md-3 prof_con">
                    <div class="profile-sidebar prof_con">
                        <!-- SIDEBAR USERPIC -->
                        <div class="profile-userpic" style="width:100%" >
                            <img style="width:200px ; height:200px ; border-radius:50%;margin-left:150px" src=" {% if profile.userphoto  %} {{profile.userphoto.url}} {% else %} {% static 'assets/img/download.png'  %}   {% endif %}" class="img-responsive" alt=""  >
                        </div>
                        <hr>
                        <!-- END SIDEBAR USERPIC -->
                        <!-- SIDEBAR USER TITLE -->
                        <div class="profile-usertitle">
                            <div class="profile-usertitle-name">
                                USerName : {{profile.user}}
                            </div>
                            <hr>
                            <div class="profile-usertitle-job">
                                Bio : {{profile.bio}}
                            </div>
                            <hr>
                            <div class="profile-usertitle-job">
                                Head Line : {{profile.headline}}
                            </div>
                            <hr>
                            <div class="profile-usertitle-job">
                                Date : {{profile.join_date}}
                            </div>
                            <hr>
                        </div>
                        <!-- END SIDEBAR USER TITLE -->
                        <!-- SIDEBAR BUTTONS -->
                        <div class="profile-userbuttons">
                            <a href="{% url 'accounts:edit_profile' profile.slug %}" class="btn btn-success btn-sm" >Edit profile <a>
                            <a href="{% url 'accounts:change_password' profile.slug %}" class="btn btn-success btn-sm" >Change Password <a>

                        </div>

                    </div>
                </div>
                {% comment %} <div class="col-md-9">
                    {% comment %} <div class="profile-content">
                        Some user related content goes here...
                    </div> {% endcomment %}
                </div> 
            </div>
        </div>

{% endblock body %}

accounts/templates/signup.html
{% extends "base.html" %}
{% load  static %}

{% load bootstrap4 %}

{% block body %}
<div class="section-headline text-center" style="padding-top: 100px;">
  <h2>Register Form </h2>                 
</div>
<form class="form-horizontal"  method="POST">
  {% csrf_token %}
  <fieldset>
    <div id="legend">
      <legend class="">Register</legend>
    </div>

    {% bootstrap_form form %}
    <div class="control-group">
      <!-- Button -->
      <div class="controls">
        <button class="btn btn-success">Register</button>
      </div>
    </div>
  </fieldset>
</form>
{% endblock body %}

templates/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
    
<head>

    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Notes</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/try.jpg' %}" rel="icon">
    <link href="{% static 'assets/img/try.jpg' %}" rel="apple-touch-icon"> 
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/mystyle.css' %}" rel="stylesheet">


</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center">
        <div class="container d-flex justify-content-between">

        <div class="logo">
            <h1><a href="/"><span>Quick</span>Notes</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav id="navbar" class="navbar">
            {% if  user.is_authenticated %}
            <ul>
                <li><a class="nav-link scrollto" href="{% url 'notes:all_notes' %}">Your Notes</a></li>
                <li><a class="nav-link scrollto" href="{% url 'notes:note_add' %}"> Add Notes</a></li>
                <li><a class="nav-link scrollto" href="{% url 'accounts:profile' profile.slug   %}">Profile</a></li>
                <li><a class="nav-link scrollto" href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
            {% else %}
            <ul>
                <li><a class="nav-link scrollto" href="{% url 'accounts:login' %}">Login</a></li>
                <li><a class="nav-link scrollto" href="{% url 'accounts:register' %}">Signup</a></li>
                </ul>
            {% endif %}
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->
        <main id="main">
        <!-- ======= Blog Section ======= -->
        <div id="blog" class="blog-area">
        <div class="blog-inner area-padding">
            <div class="blog-overly"></div>
            <div class="container ">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">

                </div>
            </div>
            <div class="row">

                {% if messages %}
                    <ul class="messages alert alert-success" style = "margin-top: 100px; "  role="alert">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% block body %}
                    
                {% endblock body %}
                    

            </div>
            </div>
        </div>
        </div><!-- End Blog Section -->



    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer>
        <div class="footer-area">
        <div class="container">
            <div class="row">
            <div class="col-md-4">
                <div class="footer-content">
                <div class="footer-head">
                    <div class="footer-logo">
                        <h2><span>Quick</span>Notes</h2>
                    </div>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.</p>
                    <div class="footer-icons">
                        <ul>
                            <li>
                            <a href="#"><i class="bi bi-facebook"></i></a>
                            </li>
                            <li>
                            <a href="#"><i class="bi bi-twitter"></i></a>
                            </li>
                            <li>
                            <a href="#"><i class="bi bi-instagram"></i></a>
                            </li>
                            <li>
                            <a href="#"><i class="bi bi-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                </div>
            </div>
            <!-- end single footer -->
            <div class="col-md-4">
                <div class="footer-content">
                <div class="footer-head">
                    <h4>information</h4>
                    <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.
                    </p>
                    <div class="footer-contacts">
                    <p><span>Tel:</span> +123 456 789</p>
                    <p><span>Email:</span> contact@example.com</p>
                    <p><span>Working Hours:</span> 9am-5pm</p>
                    </div>
                </div>
                </div>
            </div>
            <!-- end single footer -->

            </div>
        </div>
        </div>
        <div class="footer-area-bottom">
        <div class="container">
            <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="copyright text-center">
                <p>
                    &copy; Copyright <strong>QuickNotes</strong>. All Rights Reserved
                </p>
                </div>
                <div class="credits">
                <!--
                All the links in the footer should remain intact.
                You can delete the links only if you purchased the pro version.
                Licensing information: https://bootstrapmade.com/license/
                Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=eBusiness
                -->
                Designed by <a>Mahmoud Adel</a>
                </div>
            </div>
            </div>
        </div>
        </div>
    </footer><!-- End  Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>